const state = {
  data: [],
  period: "1M",
  selected: null
};

const $ = id =>
  document.getElementById(id);

const fmtInt = n => {
  if (n === null || n === undefined || !Number.isFinite(Number(n))) {
    return "—";
  }

  return Number(n).toLocaleString("en-US");
};

const fmtPrice = n => {
  if (n === null || n === undefined || !Number.isFinite(Number(n))) {
    return "—";
  }

  return Number(n).toLocaleString(
    "en-US",
    {
      minimumFractionDigits: 2,
      maximumFractionDigits: 2
    }
  );
};

const fmtDate = s => {
  if (!s) return "—";

  return new Date(
    s + "T00:00:00"
  ).toLocaleDateString(
    "en-US",
    {
      month: "short",
      day: "numeric",
      year: "numeric"
    }
  );
};


async function init() {

  try {

    /*
     * Stage 2:
     * Read real CME PG62 data generated by GitHub Actions.
     */

    const response = await fetch(
      "data/cme-gc-history.json",
      {
        cache: "no-store"
      }
    );

    if (!response.ok) {
      throw new Error(
        `HTTP ${response.status}`
      );
    }

    const json = await response.json();

    /*
     * The parser stores every GC contract.
     *
     * The chart should use only the active contract
     * for each bulletin date.
     */

    const candles = Array.isArray(
      json.candles
    )
      ? json.candles
      : [];

    state.data = candles
      .filter(row =>
        row.is_active === true
      )
      .filter(row =>
        row.date &&
        Number.isFinite(
          Number(row.settlement)
        )
      )
      .sort(
        (a, b) =>
          a.date.localeCompare(b.date)
      );

    if (!state.data.length) {
      throw new Error(
        "No active-contract CME data found."
      );
    }

    updateLiveStatus();

    bind();
    render();

    if ("serviceWorker" in navigator) {

      navigator.serviceWorker
        .register("sw.js")
        .catch(() => {});
    }

  } catch (error) {

    console.error(error);

    showError(
      "CME data could not be loaded."
    );
  }
}


function updateLiveStatus() {

  const status =
    document.querySelector(
      ".status"
    );

  if (status) {

    status.innerHTML =
      '<span class="dot"></span> CME PDF';
  }

  const footer =
    document.querySelector(
      "footer"
    );

  if (footer) {

    footer.textContent =
      "CME Daily Bulletin PG62 · Manual PDF import · "
      + "Active Contract = highest GC volume";
  }
}


function showError(message) {

  const status =
    document.querySelector(
      ".status"
    );

  if (status) {

    status.textContent = "ERROR";
  }

  const settlement =
    $("settlement");

  if (settlement) {

    settlement.textContent = "—";
  }

  const settlementDate =
    $("settlementDate");

  if (settlementDate) {

    settlementDate.textContent =
      message;
  }
}


function bind() {

  document
    .querySelectorAll(
      ".periods button"
    )
    .forEach(btn => {

      btn.addEventListener(
        "click",
        () => {

          document
            .querySelectorAll(
              ".periods button"
            )
            .forEach(
              b =>
                b.classList.remove(
                  "active"
                )
            );

          btn.classList.add(
            "active"
          );

          state.period =
            btn.dataset.period;

          state.selected = null;

          render();
        }
      );
    });


  [
    "priceChart",
    "volumeChart",
    "oiChart"
  ].forEach(id => {

    const canvas = $(id);

    if (!canvas) return;

    canvas.addEventListener(
      "click",
      e =>
        selectFromChart(
          id,
          e
        )
    );
  });
}


function sliceData() {

  const counts = {
    "1M": 22,
    "3M": 66,
    "6M": 132,
    "1Y": 252
  };

  return state.data.slice(
    -counts[state.period]
  );
}


function render() {

  if (!state.data.length) {
    return;
  }

  const latest =
    state.data[
      state.data.length - 1
    ];

  /*
   * Header.
   */

  $("contract").textContent =
    latest.contract;

  const contractName =
    document.querySelector(
      ".contract-name"
    );

  if (contractName) {

    contractName.textContent =
      `Gold Futures · ${contractMonthName(
        latest.contract
      )}`;
  }

  $("settlement").textContent =
    "$" +
    fmtPrice(
      latest.settlement
    );

  $("settlementDate").textContent =
    fmtDate(latest.date);

  $("volume").textContent =
    fmtInt(latest.volume);

  $("oi").textContent =
    fmtInt(
      latest.open_interest
    );

  const oiChange =
    Number(latest.oi_change || 0);

  $("oiChange").textContent =
    (oiChange >= 0 ? "+" : "") +
    fmtInt(oiChange);

  const rows =
    sliceData();

  drawLine(
    $("priceChart"),
    rows,
    "settlement",
    true
  );

  drawBars(
    $("volumeChart"),
    rows,
    "volume"
  );

  drawLine(
    $("oiChart"),
    rows,
    "open_interest",
    false
  );

  if (state.selected) {
    showDetail(
      state.selected
    );
  }
}


function contractMonthName(contract) {

  if (!contract || contract.length < 5) {
    return contract || "Gold Futures";
  }

  const monthCode =
    contract.slice(0, 3);

  const year =
    2000 +
    Number(
      contract.slice(3)
    );

  const names = {
    JAN: "Jan",
    FEB: "Feb",
    MAR: "Mar",
    APR: "Apr",
    MAY: "May",
    JUN: "Jun",
    JUL: "Jul",
    AUG: "Aug",
    SEP: "Sep",
    OCT: "Oct",
    NOV: "Nov",
    DEC: "Dec"
  };

  return (
    `${names[monthCode] || monthCode} ${year}`
  );
}


function chartGeometry(canvas) {

  const dpr =
    Math.max(
      1,
      window.devicePixelRatio || 1
    );

  const rect =
    canvas.getBoundingClientRect();

  canvas.width =
    Math.round(
      rect.width * dpr
    );

  canvas.height =
    Math.round(
      rect.height * dpr
    );

  const ctx =
    canvas.getContext("2d");

  ctx.setTransform(
    dpr,
    0,
    0,
    dpr,
    0,
    0
  );

  return {
    ctx,
    w: rect.width,
    h: rect.height,
    pad: {
      l: 45,
      r: 8,
      t: 8,
      b: 25
    }
  };
}


function scale(
  values,
  min,
  max,
  y0,
  y1
) {

  return value =>
    y1 -
    (
      (value - min) /
      (max - min || 1)
    ) *
    (y1 - y0);
}


function baseChart(
  canvas,
  rows,
  key
) {

  const validRows =
    rows.filter(row =>
      Number.isFinite(
        Number(row[key])
      )
    );

  const g =
    chartGeometry(canvas);

  const {
    ctx,
    w,
    h,
    pad
  } = g;

  ctx.clearRect(
    0,
    0,
    w,
    h
  );

  if (!validRows.length) {
    return {
      g,
      x: () => 0,
      y: () => 0,
      min: 0,
      max: 0,
      rows: []
    };
  }

  const vals =
    validRows.map(
      row => Number(row[key])
    );

  let min =
    Math.min(...vals);

  let max =
    Math.max(...vals);

  /*
   * Give a little breathing room when all values
   * are identical.
   */

  if (min === max) {

    const padding =
      Math.max(
        Math.abs(min) * 0.01,
        1
      );

    min -= padding;
    max += padding;
  }

  const y =
    scale(
      vals,
      min,
      max,
      pad.t,
      h - pad.b
    );

  const x =
    index =>
      pad.l +
      index *
      (
        (w - pad.l - pad.r) /
        Math.max(
          1,
          validRows.length - 1
        )
      );

  ctx.font =
    "10px -apple-system,BlinkMacSystemFont,sans-serif";

  ctx.strokeStyle =
    "#252b33";

  ctx.fillStyle =
    "#737e8c";

  ctx.lineWidth = 1;

  /*
   * Horizontal grid lines.
   */

  for (let j = 0; j < 4; j++) {

    const yy =
      pad.t +
      j *
      (
        (h - pad.t - pad.b) /
        3
      );

    ctx.beginPath();

    ctx.moveTo(
      pad.l,
      yy
    );

    ctx.lineTo(
      w - pad.r,
      yy
    );

    ctx.stroke();

    const value =
      max -
      (
        (max - min) *
        j /
        3
      );

    ctx.textAlign =
      "left";

    ctx.fillText(
      key === "settlement"
        ? fmtPrice(value)
        : fmtInt(Math.round(value)),
      3,
      yy + 3
    );
  }

  /*
   * X-axis labels.
   *
   * Old code could draw both "last interval"
   * and "last point", causing the final labels
   * to overlap.
   *
   * This version chooses at most 5 unique positions.
   */

  const labelCount =
    Math.min(
      5,
      validRows.length
    );

  const labelIndexes =
    new Set();

  if (labelCount === 1) {

    labelIndexes.add(0);

  } else {

    for (
      let j = 0;
      j < labelCount;
      j++
    ) {

      const index =
        Math.round(
          j *
          (
            (validRows.length - 1) /
            (labelCount - 1)
          )
        );

      labelIndexes.add(index);
    }
  }

  [...labelIndexes]
    .sort((a, b) => a - b)
    .forEach(index => {

      const row =
        validRows[index];

      const xx =
        x(index);

      if (index === 0) {

        ctx.textAlign = "left";

      } else if (
        index === validRows.length - 1
      ) {

        ctx.textAlign = "right";

      } else {

        ctx.textAlign = "center";
      }

      ctx.fillText(
        row.date.slice(5),
        xx,
        h - 6
      );
    });

  return {
    g,
    x,
    y,
    min,
    max,
    rows: validRows
  };
}


function drawLine(
  canvas,
  rows,
  key,
  price
) {

  const {
    g,
    x,
    y,
    rows: validRows
  } =
    baseChart(
      canvas,
      rows,
      key
    );

  const ctx =
    g.ctx;

  if (!validRows.length) {
    return;
  }

  ctx.strokeStyle =
    "#d8b46a";

  ctx.lineWidth = 2;

  ctx.beginPath();

  validRows.forEach(
    (row, index) => {

      const xx =
        x(index);

      const yy =
        y(
          Number(
            row[key]
          )
        );

      if (index === 0) {

        ctx.moveTo(
          xx,
          yy
        );

      } else {

        ctx.lineTo(
          xx,
          yy
        );
      }
    }
  );

  ctx.stroke();

  /*
   * Last-point marker.
   */

  const last =
    validRows.length - 1;

  ctx.fillStyle =
    "#f4f6f8";

  ctx.beginPath();

  ctx.arc(
    x(last),
    y(
      Number(
        validRows[last][key]
      )
    ),
    3.5,
    0,
    Math.PI * 2
  );

  ctx.fill();
}


function drawBars(
  canvas,
  rows,
  key
) {

  const {
    g,
    x,
    y,
    rows: validRows
  } =
    baseChart(
      canvas,
      rows,
      key
    );

  const ctx =
    g.ctx;

  if (!validRows.length) {
    return;
  }

  const bottom =
    g.h - g.pad.b;

  const barW =
    Math.max(
      1,
      (
        (g.w - g.pad.l - g.pad.r) /
        validRows.length
      ) * 0.72
    );

  validRows.forEach(
    (row, index) => {

      const yy =
        y(
          Number(
            row[key]
          )
        );

      ctx.fillStyle =
        "#7f8b99";

      ctx.fillRect(
        x(index) - barW / 2,
        yy,
        barW,
        bottom - yy
      );
    }
  );
}


function selectFromChart(
  id,
  event
) {

  const rows =
    sliceData();

  const canvas =
    $(id);

  const rect =
    canvas.getBoundingClientRect();

  const px =
    event.clientX -
    rect.left;

  if (
    rows.length === 0
  ) {
    return;
  }

  const index =
    Math.round(
      (
        px - 45
      ) /
      (
        rect.width - 45 - 8
      ) *
      Math.max(
        0,
        rows.length - 1
      )
    );

  if (
    index >= 0 &&
    index < rows.length
  ) {

    state.selected =
      rows[index];

    showDetail(
      rows[index]
    );
  }
}


function showDetail(d) {

  const oiChange =
    Number(
      d.oi_change || 0
    );

  const vals = [
    fmtDate(d.date),
    d.contract,
    "$" +
      fmtPrice(
        d.settlement
      ),
    fmtInt(d.volume),
    fmtInt(
      d.open_interest
    ),
    (
      oiChange >= 0
        ? "+"
        : ""
    ) +
      fmtInt(oiChange)
  ];

  document
    .querySelector(
      "#detail .detail-grid"
    )
    .innerHTML = `
      <span>Date</span>
      <b>${vals[0]}</b>

      <span>Contract</span>
      <b>${vals[1]}</b>

      <span>Settlement</span>
      <b>${vals[2]}</b>

      <span>Volume</span>
      <b>${vals[3]}</b>

      <span>Open Interest</span>
      <b>${vals[4]}</b>

      <span>OI Change</span>
      <b>${vals[5]}</b>
    `;
}


window.addEventListener(
  "resize",
  () => render()
);


init();
