#!/usr/bin/env python3

import json
import subprocess
import sys
from pathlib import Path


# ============================================================
# Paths
# ============================================================

ROOT = Path(__file__).resolve().parent.parent

# 本番と同じPG64データフォルダを直接読む
PG64_DIR = ROOT / "data" / "cme-pg64"

# テスト結果のJSON出力先
OUT = ROOT / "pg64_tests" / "out"
OUT.mkdir(parents=True, exist_ok=True)

# テスト対象Parser
PARSER = ROOT / "scripts" / "parse_pg64_v1.py"


# ============================================================
# PG64 PDF discovery
# ============================================================

def get_pg64_files():
    """
    data/cme-pg64/ にあるPDFをすべてテスト対象にする。

    ファイル名は固定しない。
    新しいPDFを追加すれば、自動的に次回テスト対象になる。
    """
    if not PG64_DIR.exists():
        raise AssertionError(
            f"PG64 data directory not found: {PG64_DIR}"
        )

    files = sorted(PG64_DIR.glob("*.pdf"))

    if not files:
        raise AssertionError(
            f"No PG64 PDF files found in: {PG64_DIR}"
        )

    return files


# ============================================================
# Parser execution
# ============================================================

def run_parser(pdf_path):
    """
    1つのPG64 PDFをParserに渡してJSONを取得する。
    """

    output_name = pdf_path.stem + ".json"
    out = OUT / output_name

    result = subprocess.run(
        [
            sys.executable,
            str(PARSER),
            str(pdf_path),
            "-o",
            str(out),
        ],
        capture_output=True,
        text=True,
    )

    # Parser自体がエラー終了した場合
    if result.returncode != 0:
        raise AssertionError(
            "\n"
            f"PG64 parser failed\n"
            f"PDF: {pdf_path}\n"
            f"returncode: {result.returncode}\n"
            f"\n--- stdout ---\n"
            f"{result.stdout}\n"
            f"\n--- stderr ---\n"
            f"{result.stderr}\n"
        )

    # JSONが生成されたか確認
    assert out.exists(), (
        f"Parser did not create output JSON:\n"
        f"PDF: {pdf_path}\n"
        f"Expected: {out}"
    )

    try:
        data = json.loads(
            out.read_text(encoding="utf-8")
        )
    except json.JSONDecodeError as e:
        raise AssertionError(
            f"Invalid JSON generated by parser:\n"
            f"PDF: {pdf_path}\n"
            f"JSON: {out}\n"
            f"Error: {e}"
        ) from e

    return data


# ============================================================
# Basic file / parser tests
# ============================================================

def test_parser_exists():
    """
    Parserが存在すること。
    """
    assert PARSER.exists(), (
        f"Parser not found: {PARSER}"
    )


def test_pg64_directory_exists():
    """
    本番PG64データディレクトリが存在すること。
    """
    assert PG64_DIR.exists(), (
        f"PG64 data directory not found: {PG64_DIR}"
    )


def test_pg64_pdf_files_exist():
    """
    data/cme-pg64/ にPDFが1つ以上存在すること。
    """
    files = get_pg64_files()

    print()
    print("PG64 PDFs found:")
    for path in files:
        print(f"  - {path.name}")

    assert len(files) > 0


# ============================================================
# Main regression test
# ============================================================

def test_pg64_all_pdfs():
    """
    data/cme-pg64/ に存在する全PG64 PDFをParserに投入する。

    日付やファイル名は固定しない。
    """

    files = get_pg64_files()

    print()
    print("=" * 70)
    print("PG64 REGRESSION TEST")
    print("=" * 70)
    print(f"Directory : {PG64_DIR}")
    print(f"PDF count : {len(files)}")
    print()

    for pdf_path in files:

        print("-" * 70)
        print(f"Testing: {pdf_path.name}")

        data = run_parser(pdf_path)

        # ----------------------------------------------------
        # Parser output structure
        # ----------------------------------------------------

        assert isinstance(data, list), (
            f"Parser output must be a list: {pdf_path.name}"
        )

        assert len(data) > 0, (
            f"Parser returned an empty list: {pdf_path.name}"
        )

        # 今のParser仕様では最初の要素がbulletin
        bulletin = data[0]

        assert isinstance(bulletin, dict), (
            f"Parser bulletin must be a dict: {pdf_path.name}"
        )

        assert "bulletin" in bulletin, (
            f"Missing 'bulletin': {pdf_path.name}"
        )

        assert "rows" in bulletin, (
            f"Missing 'rows': {pdf_path.name}"
        )

        assert "totals" in bulletin, (
            f"Missing 'totals': {pdf_path.name}"
        )

        # ----------------------------------------------------
        # Bulletin validation
        # ----------------------------------------------------

        bulletin_info = bulletin["bulletin"]

        assert isinstance(bulletin_info, dict), (
            f"'bulletin' must be a dict: {pdf_path.name}"
        )

        # Bulletin number
        assert bulletin_info.get("bulletin_number") is not None, (
            f"Missing bulletin_number: {pdf_path.name}"
        )

        # Status
        status = bulletin_info.get("bulletin_status")

        assert status in {
            "PRELIMINARY",
            "FINAL",
        }, (
            f"Invalid bulletin_status={status!r}: "
            f"{pdf_path.name}"
        )

        # ----------------------------------------------------
        # Rows validation
        # ----------------------------------------------------

        rows = bulletin["rows"]

        assert isinstance(rows, list), (
            f"'rows' must be a list: {pdf_path.name}"
        )

        assert len(rows) > 0, (
            f"No rows parsed: {pdf_path.name}"
        )

        # Gold option rowsだけを見る
        gold_rows = [
            row
            for row in rows
            if row.get("product_family_label")
        ]

        assert gold_rows, (
            f"No rows with product_family_label: "
            f"{pdf_path.name}"
        )

        # ----------------------------------------------------
        # Row-level validation
        # ----------------------------------------------------

        allowed_option_types = {
            "CALL",
            "PUT",
            "UNKNOWN",
            None,
        }

        for row in gold_rows:

            # product_family_label
            assert row.get("product_family_label"), (
                f"Missing product_family_label: "
                f"{pdf_path.name}\n"
                f"row={row}"
            )

            # option_type
            assert row.get("option_type") in allowed_option_types, (
                f"Invalid option_type="
                f"{row.get('option_type')!r}: "
                f"{pdf_path.name}\n"
                f"row={row}"
            )

            # strike
            #
            # TOTAL等の特殊行をParserがrowsに入れている場合、
            # strike=Noneを許容する。
            #
            # 通常のoption rowではstrikeが必要。
            if row.get("product_code") is not None:
                assert row.get("strike") is not None, (
                    f"Missing strike for parsed product row: "
                    f"{pdf_path.name}\n"
                    f"row={row}"
                )

            # product_codeがNoneの場合は
            # unresolved familyとして許容する。
            #
            # ここでは無理に推測してcodeを作らない。
            if row.get("product_code") is None:
                assert row.get("product_family_label"), (
                    f"Unresolved row has no family label: "
                    f"{pdf_path.name}\n"
                    f"row={row}"
                )

        # ----------------------------------------------------
        # Product code validation
        # ----------------------------------------------------

        product_codes = {
            row.get("product_code")
            for row in gold_rows
            if row.get("product_code") is not None
        }

        assert product_codes, (
            f"No product_code parsed: {pdf_path.name}"
        )

        # ----------------------------------------------------
        # Unresolved rows
        # ----------------------------------------------------

        unresolved = [
            row
            for row in gold_rows
            if row.get("product_code") is None
        ]

        # unresolvedは存在してもテスト失敗にはしない。
        #
        # 例えば、
        # MMG MONDAY ... WEEK...
        # のようにPDF抽出上、week numberを確定できない
        # ケースがあり得るため。
        #
        # 重要なのは、Parserが勝手に間違ったproduct_codeを
        # 作らないこと。
        for row in unresolved:
            assert row.get("product_family_label"), (
                f"Unresolved row without family label: "
                f"{pdf_path.name}\n"
                f"row={row}"
            )

        # ----------------------------------------------------
        # Print result
        # ----------------------------------------------------

        print(
            f"  bulletin_number : "
            f"{bulletin_info.get('bulletin_number')}"
        )

        print(
            f"  status          : "
            f"{bulletin_info.get('bulletin_status')}"
        )

        print(
            f"  rows            : "
            f"{len(rows)}"
        )

        print(
            f"  totals          : "
            f"{len(bulletin['totals'])}"
        )

        print(
            f"  product_codes   : "
            f"{len(product_codes)}"
        )

        print(
            f"  unresolved      : "
            f"{len(unresolved)}"
        )

        print(
            "  codes           : "
            + ", ".join(sorted(product_codes))
        )

        print(
            f"PASS: {pdf_path.name}"
        )

    print()
    print("=" * 70)
    print(
        f"ALL PG64 TESTS PASSED "
        f"({len(files)} PDFs)"
    )
    print("=" * 70)
